//first form
export const firstName = document.getElementById("firstname")
export const lastName = document.getElementById("lastname")
export const mobileNumber = document.getElementById("mobile")
export const emailId = document.getElementById("email")
export const aboutYou = document.getElementById("aboutyou")
export const linkedInProfile = document.getElementById("linkedin")
export const githubProfile = document.getElementById("github")
export const websitePortfolio = document.getElementById("website")
export const btn1Next = document.getElementById("btn1Next")
//second form
export const sslcSchoolName = document.getElementById("sslcSchoolName")
export const sslcSchoolPercentage = document.getElementById("sslcPercentage")
export const sslcStartYear = document.getElementById("sslcStartYear")
export const sslcEndYear = document.getElementById("sslcEndYear")
export const hscSchoolName = document.getElementById("hscSchoolName")
export const hscSchoolPercentage = document.getElementById("hscPercentage")
export const hscStartYear = document.getElementById("hscStartYear")
export const hscEndYear = document.getElementById("hscEndYear")
export const hscMajor = document.getElementById("hscMajor")
export const collegeName = document.getElementById("collegeName")
export const collegeDegreePercentage =
	document.getElementById("degreePercentage")
export const collegeDegree = document.getElementById("degree")
export const collegeDegreeMajor = document.getElementById("degreeMajor")
export const degreeStartYear = document.getElementById("degreeStartYear")
export const degreeEndYear = document.getElementById("degreeEndYear")
export const btn2Prev = document.getElementById("btn2Prev")
export const btn2Next = document.getElementById("btn2Next")
// third form
export const projectName = document.getElementById("projectName")
export const projectDate = document.getElementById("projectDate")
export const projectUrl = document.getElementById("projectUrl")
export const projectData = document.querySelector(".projectData")
export const projectDelete = document.querySelectorAll(".projectDelete")
export const btn3Prev = document.getElementById("btn3Prev")
export const btn3Next = document.getElementById("btn3Next")
// fourth form
export const skills = document.getElementById("skills")
export const expertise = document.getElementById("expertise")
export const skillData = document.querySelector(".skills-data")
export const expertiseData = document.querySelector(".expertise-data")
export const skillDelete = document.querySelectorAll(".skill-delete")
export const expertiseDelete = document.querySelectorAll(".expertise-delete")
export const btn4prev = document.getElementById("btn4Prev")
export const btn4Next = document.getElementById("btn4Next")
// fifth form
export const jobTitle = document.getElementById("jobTitle")
export const companyName = document.getElementById("companyName")
export const employmentType = document.getElementById("employmentType")
export const jobLocation = document.getElementById("jobLocation")
export const jobStartYear = document.getElementById("jobStartYear")
export const jobEndYear = document.getElementById("jobEndYear")
export const jobDescription = document.getElementById("jobDescription")
export const btn5Prev = document.getElementById("btn5Prev")
export const btn5Next = document.getElementById("btn5Next")
// sixth form
export const interest = document.getElementById("interest")
export const interestData = document.querySelector(".interest-data")
export const interestDelete = document.querySelectorAll(".interest-delete")
export const btn6Prev = document.getElementById("btn6Prev")
export const btn6Next = document.getElementById("btn6Next")
// seventh form
export const profileImage = document.getElementById("profileImage")
export const uploadBox = document.querySelector(".upload-box")
export const uploadImage = document.querySelector(".upload-img")
export const previewBox = document.querySelector(".preview-box")
export const previewImg = document.querySelector(".previewImg")
export const discardImg = document.getElementById("discard-img")
export const btn7Prev = document.getElementById("btn7Prev")
export const btn7Next = document.getElementById("btn7Next")
// sections
export const createResume1 = document.getElementById("create-resume1")
export const createResume2 = document.getElementById("create-resume2")
export const createResume3 = document.getElementById("create-resume3")
export const createResume4 = document.getElementById("create-resume4")
export const createResume5 = document.getElementById("create-resume5")
export const createResume6 = document.getElementById("create-resume6")
export const createResume7 = document.getElementById("create-resume7")
export const formText = document.querySelectorAll(".form-text")
export const formControl = document.querySelectorAll(".form-control")
export const formSelect = document.querySelectorAll(".form-select")
export const textArea = document.querySelectorAll("textarea")
export const skip = document.querySelector(".skip")
